FROM node:23-alpine

RUN npm i -g pnpm

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/http ./apps/http

RUN pnpm install
RUN pnpm run db:generate
RUN pnpm run db:generate

EXPOSE 3000

CMD ["npm", "run", "start:http"]

