// Seeds the element catalogue and the default GEC Bilaspur campus map.
// Safe to re-run: elements are upserted by id and the map's elements are replaced.
// The map data is generated by tools/campus-map/generate.py.
const path = require("path");
const client = require("../client.js");
const { attachPortals } = require("../spaces.js");
const campus = require(path.join(__dirname, "../prisma/maps/gec-bilaspur.json"));
const avatars = require(path.join(__dirname, "../prisma/avatars.json"));

async function seedLegacyTiles() {
    for (let i = 1; i < 82; i++) {
        const id = `hightile-${i}`;
        const data = {
            imageUrl: `/Tiles/HighTiles/HighTiles${i}.png`,
            width: 1,
            height: 1,
            static: false,
            layer: "floor",
        };
        await client.element.upsert({ where: { id }, create: { id, ...data }, update: data });
    }
}

async function seedCampus() {
    for (const { id, ...data } of campus.elements) {
        await client.element.upsert({ where: { id }, create: { id, ...data }, update: data });
    }

    const { id, ...mapData } = campus.map;
    await client.$transaction([
        client.map.upsert({ where: { id }, create: { id, ...mapData }, update: mapData }),
        client.mapElements.deleteMany({ where: { mapId: id } }),
        client.mapElements.createMany({
            data: campus.placements.map((p) => ({ mapId: id, elementId: p.elementId, x: p.x, y: p.y })),
        }),
    ]);
    console.log(`Seeded "${mapData.name}" with ${campus.placements.length} placements`);

    // building interiors: one map each, same element/placement shape as the campus
    for (const interior of campus.interiors ?? []) {
        for (const { id: eid, ...data } of interior.elements) {
            await client.element.upsert({ where: { id: eid }, create: { id: eid, ...data }, update: data });
        }
        const { id: mid, ...mdata } = interior.map;
        await client.$transaction([
            client.map.upsert({ where: { id: mid }, create: { id: mid, ...mdata }, update: mdata }),
            client.mapElements.deleteMany({ where: { mapId: mid } }),
            client.mapElements.createMany({
                data: interior.placements.map((p) => ({ mapId: mid, elementId: p.elementId, x: p.x, y: p.y })),
            }),
        ]);
    }
    // door portals: campus -> interior and interior -> campus
    const mapIds = [id, ...(campus.interiors ?? []).map((i) => i.map.id)];
    await client.$transaction([
        client.mapPortal.deleteMany({ where: { mapId: { in: mapIds } } }),
        client.mapPortal.createMany({ data: campus.portals ?? [] }),
    ]);
    console.log(`Seeded ${(campus.interiors ?? []).length} interiors and ${(campus.portals ?? []).length} portals`);
}

// Spaces created from an earlier version of the campus map keep that version's
// placements. Any space that still references a campus element the current map no
// longer uses is rebuilt from the current map: elements replaced, size and spawn
// updated. Notes pinned on its old boards are lost (they cascade with the board rows).
async function migrateCampusSpaces() {
    const current = new Set(campus.elements.map((e) => e.id));
    const stale = await client.spaceElements.findMany({
        where: { elementId: { startsWith: "campus-", notIn: [...current] } },
        select: { spaceId: true },
        distinct: ["spaceId"],
    });
    for (const { spaceId } of stale) {
        await client.$transaction([
            client.spaceElements.deleteMany({ where: { spaceId } }),
            client.spaceElements.createMany({
                data: campus.placements.map((p) => ({ spaceId, elementId: p.elementId, x: p.x, y: p.y })),
            }),
            client.space.update({
                where: { id: spaceId },
                data: { width: campus.map.width, height: campus.map.height, thumbnail: campus.map.thumbnail,
                        spawnX: campus.map.spawnX, spawnY: campus.map.spawnY },
            }),
        ]);
    }
    if (stale.length) console.log(`Rebuilt ${stale.length} space(s) from the current campus map`);

    // campus spaces without interiors yet (made before portals, or just rebuilt) get them now
    const campusSpaces = await client.space.findMany({
        where: { parentId: null, elements: { some: { elementId: "campus-gate-arch" } }, portals: { none: {} } },
        select: { id: true },
    });
    for (const { id: spaceId } of campusSpaces) {
        await client.$transaction((tx) => attachPortals(tx, spaceId, campus.map.id), { timeout: 60_000 });
    }
    if (campusSpaces.length) console.log(`Attached interiors to ${campusSpaces.length} campus space(s)`);
}

// Generated by tools/avatars/generate.py
async function seedAvatars() {
    for (const { id, ...data } of avatars) {
        await client.avatar.upsert({ where: { id }, create: { id, ...data }, update: data });
    }
    console.log(`Seeded ${avatars.length} avatars`);
}

const OFFICE = "/Office";
const LAB = "/Lab";

// Element catalogue, shared by every map. `static` is the collision flag;
// `layer` drives draw order (floor -> wall -> objects -> player -> topObjects).
// Seats (chair, couch, stool) are non-static so players can stand on and sit
// in them; the WS server treats those imageUrls as seat tiles.
const ELEMENTS = {
  carpet: { imageUrl: `${OFFICE}/floor-carpet.png`, width: 1, height: 1, static: false, layer: "floor" },
  wood: { imageUrl: `${OFFICE}/floor-wood.png`, width: 1, height: 1, static: false, layer: "floor" },
  tile: { imageUrl: `${OFFICE}/floor-tile.png`, width: 1, height: 1, static: false, layer: "floor" },

  wallH: { imageUrl: `${OFFICE}/wall-h.png`, width: 1, height: 1, static: true, layer: "wall" },
  wallV: { imageUrl: `${OFFICE}/wall-v.png`, width: 1, height: 1, static: true, layer: "wall" },
  wallCorner: { imageUrl: `${OFFICE}/wall-corner.png`, width: 1, height: 1, static: true, layer: "wall" },
  door: { imageUrl: `${OFFICE}/door.png`, width: 1, height: 1, static: false, layer: "wall" },

  desk: { imageUrl: `${OFFICE}/desk.png`, width: 2, height: 1, static: true, layer: "objects" },
  chair: { imageUrl: `${OFFICE}/chair.png`, width: 1, height: 1, static: false, layer: "objects" },
  monitor: { imageUrl: `${OFFICE}/monitor.png`, width: 1, height: 1, static: true, layer: "objects" },
  plant: { imageUrl: `${OFFICE}/plant.png`, width: 1, height: 1, static: true, layer: "objects" },
  couch: { imageUrl: `${OFFICE}/couch.png`, width: 2, height: 1, static: false, layer: "objects" },
  confTable: { imageUrl: `${OFFICE}/conf-table.png`, width: 3, height: 2, static: true, layer: "objects" },
  whiteboard: { imageUrl: `${OFFICE}/whiteboard.png`, width: 2, height: 1, static: true, layer: "objects" },
  coffee: { imageUrl: `${OFFICE}/coffee.png`, width: 1, height: 1, static: true, layer: "objects" },
  bookshelf: { imageUrl: `${OFFICE}/bookshelf.png`, width: 1, height: 1, static: true, layer: "objects" },
  rug: { imageUrl: `${OFFICE}/rug.png`, width: 2, height: 2, static: false, layer: "floor" },

  lamp: { imageUrl: `${OFFICE}/lamp.png`, width: 1, height: 1, static: false, layer: "topObjects" },

  // --- lab-specific ---------------------------------------------------
  labFloor: { imageUrl: `${LAB}/floor-lab.png`, width: 1, height: 1, static: false, layer: "floor" },
  labBench: { imageUrl: `${LAB}/lab-bench.png`, width: 2, height: 1, static: true, layer: "objects" },
  pcTower: { imageUrl: `${LAB}/pc-tower.png`, width: 1, height: 1, static: true, layer: "objects" },
  projector: { imageUrl: `${LAB}/projector-screen.png`, width: 2, height: 1, static: true, layer: "objects" },
  serverRack: { imageUrl: `${LAB}/server-rack.png`, width: 1, height: 2, static: true, layer: "objects" },
  oscilloscope: { imageUrl: `${LAB}/oscilloscope.png`, width: 1, height: 1, static: true, layer: "objects" },
  breadboard: { imageUrl: `${LAB}/breadboard.png`, width: 1, height: 1, static: true, layer: "objects" },
  toolRack: { imageUrl: `${LAB}/tool-rack.png`, width: 1, height: 1, static: true, layer: "objects" },
  stool: { imageUrl: `${LAB}/stool.png`, width: 1, height: 1, static: false, layer: "objects" },
};

/** Collects placements as { key, x, y } for one map. */
function placer() {
  const placements = [];
  const put = (key, x, y) => placements.push({ key, x, y });
  return { placements, put };
}

/** Walls the perimeter of a w x h map, with a door at `doorX` on the bottom. */
function perimeter(put, w, h, doorX) {
  for (let x = 0; x < w; x++) {
    put(x === 0 || x === w - 1 ? "wallCorner" : "wallH", x, 0);
    if (x === doorX) put("door", x, h - 1);
    else put(x === 0 || x === w - 1 ? "wallCorner" : "wallH", x, h - 1);
  }
  for (let y = 1; y < h - 1; y++) {
    put("wallV", 0, y);
    put("wallV", w - 1, y);
  }
}

// ---------------------------------------------------------------- office

const OFFICE_W = 30;
const OFFICE_H = 20;
const ROOM = { x0: 20, y0: 1, x1: 28, y1: 8 }; // meeting room, top-right

function buildOffice() {
  const { placements, put } = placer();

  // Carpet everywhere inside the perimeter; lounge is wood, coffee corner tiled.
  const floorAt = new Map();
  for (let y = 1; y < OFFICE_H - 1; y++) {
    for (let x = 1; x < OFFICE_W - 1; x++) floorAt.set(`${x},${y}`, "carpet");
  }
  for (let y = 12; y <= 18; y++) for (let x = 1; x <= 8; x++) floorAt.set(`${x},${y}`, "wood");
  for (let y = 15; y <= 18; y++) for (let x = 13; x <= 18; x++) floorAt.set(`${x},${y}`, "tile");
  for (const [pos, key] of floorAt) {
    const [x, y] = pos.split(",").map(Number);
    put(key, x, y);
  }

  perimeter(put, OFFICE_W, OFFICE_H, 15);

  // Meeting room partition, with its own door.
  const ROOM_DOOR_Y = 5;
  for (let y = ROOM.y0; y <= ROOM.y1; y++) {
    if (y === ROOM_DOOR_Y) put("door", ROOM.x0 - 1, y);
    else put("wallV", ROOM.x0 - 1, y);
  }
  for (let x = ROOM.x0 - 1; x <= ROOM.x1; x++) put("wallH", x, ROOM.y1 + 1);

  put("confTable", 23, 4);
  for (const x of [23, 24, 25]) {
    put("chair", x, 3);
    put("chair", x, 6);
  }
  put("chair", 22, 4);
  put("chair", 22, 5);
  put("chair", 26, 4);
  put("chair", 26, 5);
  put("whiteboard", 23, 1);
  put("plant", 27, 7);

  // Open plan: four pods of desk + monitor + two chairs.
  for (const [dx, dy] of [[3, 3], [9, 3], [3, 8], [9, 8]]) {
    put("desk", dx, dy);
    put("monitor", dx, dy);
    put("chair", dx, dy + 1);
    put("chair", dx + 1, dy + 1);
  }
  put("plant", 7, 3);
  put("plant", 13, 8);
  put("bookshelf", 27, 12);
  put("bookshelf", 27, 13);
  put("bookshelf", 27, 14);

  // Lounge on the wood floor.
  put("rug", 3, 14);
  put("couch", 3, 13);
  put("plant", 2, 13);
  put("plant", 6, 13);
  put("plant", 1, 18);

  // Coffee corner on the tiles.
  put("coffee", 14, 16);
  put("coffee", 15, 16);
  put("bookshelf", 17, 16);
  put("plant", 18, 18);

  for (const [lx, ly] of [[6, 2], [12, 2], [6, 10], [12, 10], [24, 2]]) put("lamp", lx, ly);

  return placements;
}

// ---------------------------------------------------------------- lab

const LAB_W = 24;
const LAB_H = 16;

function buildLab() {
  const { placements, put } = placer();

  // Vinyl lab flooring throughout; the server corner is tiled.
  for (let y = 1; y < LAB_H - 1; y++) {
    for (let x = 1; x < LAB_W - 1; x++) {
      const serverCorner = x >= 17 && y <= 6;
      put(serverCorner ? "tile" : "labFloor", x, y);
    }
  }

  perimeter(put, LAB_W, LAB_H, 12);

  // Front of room: projector screen and whiteboard on the top wall, with the
  // instructor's desk below them.
  put("projector", 7, 1);
  put("whiteboard", 12, 1);
  put("desk", 9, 3);
  put("monitor", 9, 3);
  put("chair", 9, 4);

  // Three rows of student workstations. Each bench seats two: a monitor and a
  // tower on the benchtop, stools in front.
  for (const rowY of [7, 10, 13]) {
    for (const bx of [2, 5, 8, 11]) {
      put("labBench", bx, rowY);
      put("monitor", bx, rowY);
      put("pcTower", bx + 1, rowY);
      put("stool", bx, rowY + 1);
      put("stool", bx + 1, rowY + 1);
    }
  }

  // Networking corner: two racks and a tool rack against the tiled floor.
  put("serverRack", 18, 2);
  put("serverRack", 20, 2);
  put("toolRack", 22, 2);
  put("bookshelf", 22, 5);

  // Electronics benches down the right-hand side.
  for (const by of [9, 12]) {
    put("labBench", 17, by);
    put("oscilloscope", 17, by);
    put("breadboard", 18, by);
    put("stool", 17, by + 1);
    put("stool", 18, by + 1);

    put("labBench", 20, by);
    put("breadboard", 20, by);
    put("oscilloscope", 21, by);
    put("stool", 20, by + 1);
    put("stool", 21, by + 1);
  }

  put("plant", 1, 1);
  put("plant", 22, 14);
  put("toolRack", 15, 2);

  for (const [lx, ly] of [[4, 5], [10, 5], [4, 11], [10, 11], [19, 8]]) put("lamp", lx, ly);

  return placements;
}

// ---------------------------------------------------------------- maps

const MAPS = [
  {
    name: "Default Office",
    width: OFFICE_W,
    height: OFFICE_H,
    thumbnail: `${OFFICE}/conf-table.png`,
    build: buildOffice,
  },
  {
    name: "College Lab",
    width: LAB_W,
    height: LAB_H,
    thumbnail: `${LAB}/lab-bench.png`,
    build: buildLab,
  },
];

async function upsertMapElements() {
  const ids = {};
  for (const [key, spec] of Object.entries(ELEMENTS)) {
    const existing = await client.element.findFirst({ where: { imageUrl: spec.imageUrl } });
    const element = existing
      ? await client.element.update({ where: { id: existing.id }, data: spec })
      : await client.element.create({ data: spec });
    ids[key] = element.id;
  }
  return ids;
}

// Office/lab elements have no fixed ids, so they're matched by imageUrl and
// each map is rebuilt from scratch every run.
async function seedMaps() {
  const ids = await upsertMapElements();
  for (const spec of MAPS) {
    await client.map.deleteMany({ where: { name: spec.name } });

    const placements = spec.build();
    const unknown = placements.filter((p) => !ids[p.key]);
    if (unknown.length) {
      throw new Error(`Unknown element keys in "${spec.name}": ${[...new Set(unknown.map((p) => p.key))].join(", ")}`);
    }

    const map = await client.map.create({
      data: {
        name: spec.name,
        width: spec.width,
        height: spec.height,
        thumbnail: spec.thumbnail,
        mapElements: {
          create: placements.map((p) => ({ elementId: ids[p.key], x: p.x, y: p.y })),
        },
      },
    });
    console.log(`Seeded "${spec.name}" (${map.id}) with ${placements.length} placements`);
  }
}

async function main() {
    await seedLegacyTiles();
    await seedAvatars();
    await seedCampus();
    await migrateCampusSpaces();
    await seedMaps();
    console.log("Done!");
}

main()
    .catch((err) => {
        console.error(err);
        process.exitCode = 1;
    })
    .finally(() => client.$disconnect());
