// Seeds the element catalogue and the default GEC Bilaspur campus map.
// Safe to re-run: elements are upserted by id and the map's elements are replaced.
// The map data is generated by tools/campus-map/generate.py.
const path = require("path");
const client = require("../client.js");
const campus = require(path.join(__dirname, "../prisma/maps/gec-bilaspur.json"));
const avatars = require(path.join(__dirname, "../prisma/avatars.json"));

async function seedLegacyTiles() {
    for (let i = 1; i < 82; i++) {
        const id = `hightile-${i}`;
        const data = {
            imageUrl: `/Tiles/HighTiles/HighTiles${i}.png`,
            width: 1,
            height: 1,
            static: false,
            layer: "floor",
        };
        await client.element.upsert({ where: { id }, create: { id, ...data }, update: data });
    }
}

async function seedCampus() {
    for (const { id, ...data } of campus.elements) {
        await client.element.upsert({ where: { id }, create: { id, ...data }, update: data });
    }

    const { id, ...mapData } = campus.map;
    await client.$transaction([
        client.map.upsert({ where: { id }, create: { id, ...mapData }, update: mapData }),
        client.mapElements.deleteMany({ where: { mapId: id } }),
        client.mapElements.createMany({
            data: campus.placements.map((p) => ({ mapId: id, elementId: p.elementId, x: p.x, y: p.y })),
        }),
    ]);
    console.log(`Seeded "${mapData.name}" with ${campus.placements.length} placements`);
}

// Generated by tools/avatars/generate.py
async function seedAvatars() {
    for (const { id, ...data } of avatars) {
        await client.avatar.upsert({ where: { id }, create: { id, ...data }, update: data });
    }
    console.log(`Seeded ${avatars.length} avatars`);
}

async function main() {
    await seedLegacyTiles();
    await seedAvatars();
    await seedCampus();
    console.log("Done!");
}

main()
    .catch((err) => {
        console.error(err);
        process.exitCode = 1;
    })
    .finally(() => client.$disconnect());
